export const agentNavigationLinks = [
    {
        name: "Dashboard",
        link: true,
        border: false,
        startWith: "/ag/dashboard",
        route: "ag.dashboard",
        img: "/assets/images/sidebar/dashboard.png",
        isSpecial: false,
        permissions: [],
    },
    {
        name: "Customers",
        link: false,
        border: true,
        permissions: [],
    },
    {
        name: "Users",
        link: true,
        border: false,
        startWith: "/ag/users",
        route: "ag.users.index",
        img: "/assets/images/sidebar/users.png",
        isSpecial: false,
        permissions: [],
    },
    {
        name: "Attendances",
        link: true,
        border: false,
        startWith: "/ag/attendances",
        route: "ag.attendances.index",
        img: "/assets/images/sidebar/attendees.png",
        isSpecial: false,
        permissions: [],
    },
    {
        name: "Accounting",
        link: false,
        border: true,
        permissions: [],
    },
    {
        name: "Payments",
        link: true,
        border: false,
        startWith: "/ag/payments",
        route: "ag.payments.index",
        img: "/assets/images/sidebar/subscriptions.png",
        isSpecial: false,
        permissions: [],
    },
    {
        name: "Other",
        link: false,
        border: true,
        permissions: [],
    },
    {
        name: "Maintenances",
        link: true,
        border: false,
        startWith: "/ag/maintenances",
        route: "ag.maintenances.index",
        img: "/assets/images/sidebar/subscriptions.png",
        isSpecial: false,
        permissions: [],
    },
    {
        name: "Machines",
        link: true,
        border: false,
        startWith: "/ag/machines",
        route: "ag.machines.index",
        img: "/assets/images/sidebar/subscriptions.png",
        isSpecial: false,
        permissions: [],
    },
];


export const adminNavigationLinks = [
    {
        name: "Dashboard",
        link: true,
        border: false,
        startWith: "/admin/dashboard",
        route: "ag.dashboard",
        img: "/assets/images/sidebar/dashboard.png",
        isSpecial: false,
        permissions: [],
    },
    {
        name: "Clients",
        link: false,
        border: true,
        permissions: [],
    },
    {
        name: "Businesses",
        link: true,
        border: false,
        startWith: "/dashboard",
        route: "ag.dashboard",
        img: "/assets/images/sidebar/users.png",
        isSpecial: false,
        permissions: [],
    },
    {
        name: "Accounting",
        link: false,
        border: true,
        permissions: [],
    },
    {
        name: "Payments",
        link: true,
        border: false,
        startWith: "/dashboard",
        route: "ag.dashboard",
        img: "/assets/images/sidebar/subscriptions.png",
        isSpecial: false,
        permissions: [],
    }
];
